// <auto-generated />
using System;
using FastCare.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastCare.Api.Migrations
{
    [DbContext(typeof(FastCareDbContext))]
    [Migration("20231115084936_Switched Database Fresh Migration")]
    partial class SwitchedDatabaseFreshMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("FastCare.Domain.Models.Doctor", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorBio")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorDegree")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorExperience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoctorLocation")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorRatings")
                        .HasColumnType("INTEGER");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
